version: "3"
services:
  application:
    container_name: application_container
    image: "adoptopenjdk/openjdk11:jdk-11.0.13_8"
    expose:
      - 5005
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - "ENV_VAR=value"
    working_dir: /grails_docker
    volumes:
      - .:/grails_docker
      - ./cache/gradle:/root/.gradle
      - ./cache/grails:/root/.grails
      - ./cache/m2:/root/.m2
    networks:
      - app-network
    command:
      ./grailsw run-app
      #ls
    #- "daemon off;"
    #tty: true


  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "54321:5432"
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./cache/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge


volumes:
  postgres:
  pgadmin: